---
- name: install apache
  apt:
    name: apache2
  register: install_result

- name:
  debug: var=install_result

- name: start apache
  service:
    name: apache2
    state: started

- name: copy apache2.conf file
  copy:
    src: ./files/apache2.conf
    dest: /etc/apache2/apache2.conf
  notify:
    - restart apache
