- name: install apache
  apt:
    name: apache2
  register: install_result

- name:
  debug: var=install_result

- name: start service    
  service:
    name: apache2      
    state: started

- name: copy index.html
  template:
    src: './templates/index.html.j2'
    dest: '/var/www/html/index.html'
  notify:
    - restart apache      
