- name: install apache
  apt:
    name: apache2
  register: install_result

- name:
  debug: var=install_result

- name: start service    
  service:
    name: apache2      
    state: started

- name: copy toto.txt
  copy:
    src: './files/toto.txt'
    dest: '/tmp/toto.txt'
