---
- hosts: 
    - webserver
    - dbserver  
  remote_user: root
  vars_files:
    - "vars/vars.yml"

  roles:
    - role: apache
    - role: php
    - role: mysql
  #when: ansible_os_family | lower == "ubuntu"  
