- hosts: webserver
  remote_user: root
  vars_files:
    - "vars/{{env}}_vars.yml"
    - "vars/secret_{{env}}.yml" 
  tasks:
    - name: create user
      user: 
        name: "{{user}}"
        password: "{{password | password_hash('sha512')}}"
        state: present
