- hosts: webserver
  remote_user: root
  vars_files:
    - "vars/{{env}}_vars.yml"
  tasks:
    - name: debug
      debug:
        msg: "bonjour, ici l'environnement {{env}}"
    - name: Install vim
      apt:
        name: vim
        state: "{{vim_state}}"
